### ISSUE TITLE
Decimal are localized

### ISSUE THREAD

**Issue by minirop** [robotii/sophielang#1]
Hello.

I just cloned and built the repo, but when I try the code in the readme, I get a _FormatException_ because my locale is fr-FR and `Convert.ToDouble(String)` wants a comma and not a dot for separating decimal.
It works if you add `Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");` at the start of _Main_ (but dunno if that implies other things or if I need to change other variables like `CurrentUICulture`)

Cheers.

**Comment by robotii** [comment]
Hi,

There are probably a few issues surrounding i18n in the code, as I'm working in en-GB, so probably haven't noticed them. I'll try and take a look to see if I can fix them.

I think the correct fix is to specify the locale at the point of conversion. That way you can still use your own locale when building. I don't think it's right that anyone should be forced to use a particular locale to get it to work.

**Comment by robotii** [comment]
Hi @minirop I've added a fix that should resolve this issue without having to change the default locale. Please let me know if this fixes the issue.

There may be more i18n issues in the code. As I only use English locales, I'm not really able to give it proper testing.

**Comment by minirop** [comment]
That also what I found, and it works. (see you on Wren.NET now ^^)
